/** Dados contextualizados para o setor Comércio e Varejo (moda, calçados e acessórios) */

export function isVarejoTheme(theme: unknown): boolean {
  return theme === "varejo";
}

export const VAREJO_PRODUCTS = [
  {
    id: 101,
    sku: "CAM-001",
    name: "Camiseta Classic Algodão",
    stock: 52,
    minimum: 24,
    expiration: "LOTE-2026-A",
    status: "OK" as const,
    price: 79.9,
    description: "Malha 100% algodão penteado, corte regular confortável.",
    image_url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&q=80",
    category: "Moda Masculina",
    is_promo: false,
    promo_price: 69.9,
    barcode: "7891001001001",
    unit_type: "Unidade",
    wholesale_price: 48.5,
  },
  {
    id: 102,
    sku: "TEN-002",
    name: "Tênis Casual Slip-on",
    stock: 18,
    minimum: 20,
    expiration: "LOTE-2026-B",
    status: "Baixo" as const,
    price: 219.9,
    description: "Slip-on leve, solado antiderrapante, ideal para o dia a dia.",
    image_url: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500&q=80",
    category: "Calçados",
    is_promo: true,
    promo_price: 179.9,
    barcode: "7892002002002",
    unit_type: "Unidade",
    wholesale_price: 128.0,
  },
  {
    id: 103,
    sku: "BOL-003",
    name: "Bolsa Couro Sintético",
    stock: 14,
    minimum: 10,
    expiration: "LOTE-2026-C",
    status: "OK" as const,
    price: 149.9,
    description: "Alça ajustável, compartimento interno com zíper e acabamento premium.",
    image_url: "https://images.unsplash.com/photo-1584917865442-de89d76a96c8?w=500&q=80",
    category: "Acessórios",
    is_promo: false,
    barcode: "7893003003003",
    unit_type: "Unidade",
    wholesale_price: 86.0,
  },
  {
    id: 104,
    sku: "CAL-004",
    name: "Calça Jeans Slim-Fit",
    stock: 9,
    minimum: 15,
    expiration: "LOTE-2026-D",
    status: "Baixo" as const,
    price: 169.9,
    description: "Jeans com elastano, modelagem slim, lavagem média.",
    image_url: "https://images.unsplash.com/photo-1473966962644-7e3e24439b0a?w=500&q=80",
    category: "Moda Unissex",
    is_promo: false,
    barcode: "7894004004004",
    unit_type: "Unidade",
    wholesale_price: 94.5,
  },
  {
    id: 105,
    sku: "OCU-005",
    name: "Óculos de Sol Noir",
    stock: 28,
    minimum: 12,
    expiration: "LOTE-2026-E",
    status: "OK" as const,
    price: 129.9,
    description: "Lentes UV400, armação acetato preta, estilo atemporal.",
    image_url: "https://images.unsplash.com/photo-1572635196233-2244a6320d8?w=500&q=80",
    category: "Acessórios",
    is_promo: true,
    promo_price: 99.9,
    barcode: "7895005005005",
    unit_type: "Unidade",
    wholesale_price: 62.0,
  },
  {
    id: 106,
    sku: "VES-006",
    name: "Vestido Midi Floral",
    stock: 22,
    minimum: 10,
    expiration: "LOTE-2026-F",
    status: "OK" as const,
    price: 189.9,
    description: "Estampa floral exclusiva, forro leve, caimento fluido.",
    image_url: "https://images.unsplash.com/photo-1595777457583-95e059a8aead?w=500&q=80",
    category: "Moda Feminina",
    is_promo: false,
    barcode: "7896006006006",
    unit_type: "Unidade",
    wholesale_price: 112.0,
  },
];

export function getVarejoDashboard(products = VAREJO_PRODUCTS) {
  const lowStockCount = products.filter((p) => p.stock <= p.minimum).length;
  const nearExpiryCount = products.filter((p) => p.stock <= p.minimum).length;

  return {
    weekly_revenue: 28750,
    weekly_profit: 11240,
    low_stock_count: lowStockCount,
    near_expiry_count: nearExpiryCount,
    revenue_vs_last_week: 14.8,
    profit_vs_last_week: 9.2,
    low_stock_vs_last_week: 3,
    near_expiry_vs_last_week: -1,
    sales_chart: [
      { day: "Seg", revenue: 3200, profit: 1280 },
      { day: "Ter", revenue: 4100, profit: 1650 },
      { day: "Qua", revenue: 3800, profit: 1520 },
      { day: "Qui", revenue: 5200, profit: 2100 },
      { day: "Sex", revenue: 6100, profit: 2480 },
      { day: "Sáb", revenue: 4850, profit: 1940 },
      { day: "Dom", revenue: 1500, profit: 270 },
    ],
    top_sold: [
      { id: 1, name: "Camiseta Classic Algodão", sales: 428 },
      { id: 2, name: "Tênis Casual Slip-on", sales: 186 },
      { id: 3, name: "Calça Jeans Slim-Fit", sales: 152 },
      { id: 4, name: "Óculos de Sol Noir", sales: 94 },
    ],
    inactive_products: [
      { name: "Bolsa Couro Sintético", days_inactive: 24, stock: 14 },
      { name: "Calça Jeans Slim-Fit", days_inactive: 16, stock: 9 },
      { name: "Tênis Casual Slip-on", days_inactive: 12, stock: 18 },
    ],
    monthly_totals: {
      gross_revenue: 112400,
      production_costs: 48200,
      invisible_costs: 8900,
      ifood_tax: 0,
      net_profit: 55300,
      margin_ratio: 49.2,
    },
  };
}

export const VAREJO_PROMOTIONS = [
  {
    id: 201,
    title: "Liquidação de Inverno",
    subtitle: "Jaquetas e moletons — últimas peças da coleção",
    type: "Desconto",
    discount: "-40%",
    recovery: 4200,
    status: "Sucesso",
    active: 1,
  },
  {
    id: 202,
    title: "Leve 3 Camisetas, Pague 2",
    subtitle: "Camiseta Classic Algodão — giro acelerado",
    type: "BOGO",
    discount: "L3P2",
    recovery: 2800,
    status: "Normal",
    active: 0,
  },
  {
    id: 203,
    title: "Combo Tênis + Meia Esportiva",
    subtitle: "Tênis Casual Slip-on + kit meias",
    type: "Combo",
    discount: "-25%",
    recovery: 1950,
    status: "Aviso",
    active: 0,
  },
];

export const VAREJO_SUPPLIERS = [
  {
    id: 301,
    name: "Têxtil Fios da União",
    contact: "(11) 3344-5566 / vendas@fiosdauniao.com.br",
    category: "Malhas e Tecidos",
    active: 1,
    items: ["Malha algodão 30.1", "Jeans índigo 12oz", "Linha poliéster industrial", "Etiqueta composição"],
  },
  {
    id: 302,
    name: "Central de Calçados Sul",
    contact: "(51) 99887-1122 / pedidos@calcadossul.com.br",
    category: "Calçados e Solados",
    active: 1,
    items: ["Solado EVA slip-on", "Palmilha anatômica", "Cadarço elástico", "Caixa display calçado"],
  },
  {
    id: 303,
    name: "Cabides & Tags Embalagens",
    contact: "comercial@cabidestags.com.br",
    category: "Embalagens e PDV",
    active: 1,
    items: ["Cabide acrílico", "Tag RFID", "Sacola kraft branding", "Etiqueta tamanho P/M/G/GG"],
  },
];

export const VAREJO_ORDERS = [
  {
    id: 401,
    customer_name: "Mariana Souza",
    customer_phone: "(11) 99876-5432",
    type: "Delivery",
    status: "Rota de Envio",
    items: [{ id: 102, name: "Tênis Casual Slip-on", quantity: 1, price: 219.9 }],
    total_value: 229.9,
    delivery_fee: 10.0,
    cep: "01310-100",
    rua: "Avenida Paulista",
    bairro: "Bela Vista",
    cidade: "São Paulo",
    estado: "SP",
    numero: "1200",
    complemento: "Apto 82",
    estimated_time: "2-3 dias úteis",
    driver_name: "Carlos Costa",
    driver_type: "Terceirizado",
    driver_phone: "(11) 98888-1111",
    transport_obs: "Conferir numeração 38",
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 402,
    customer_name: "Guilherme Santos",
    customer_phone: "(11) 98765-4321",
    type: "Balcão",
    status: "Pronto para Entrega",
    items: [
      { id: 101, name: "Camiseta Classic Algodão", quantity: 2, price: 79.9 },
      { id: 104, name: "Calça Jeans Slim-Fit", quantity: 1, price: 169.9 },
    ],
    total_value: 329.7,
    delivery_fee: 0,
    cep: "",
    rua: "",
    bairro: "",
    cidade: "",
    estado: "",
    numero: "",
    complemento: "",
    estimated_time: "Retirada em loja",
    driver_name: "",
    driver_type: "Próprio",
    driver_phone: "",
    transport_obs: "Separar P e M — provador 2",
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
  {
    id: 403,
    customer_name: "Ana Beatriz Lima",
    customer_phone: "(21) 97777-6666",
    type: "Delivery",
    status: "Em preparo",
    items: [
      { id: 103, name: "Bolsa Couro Sintético", quantity: 1, price: 149.9 },
      { id: 105, name: "Óculos de Sol Noir", quantity: 1, price: 129.9 },
    ],
    total_value: 289.8,
    delivery_fee: 10.0,
    cep: "22041-080",
    rua: "Rua Barata Ribeiro",
    bairro: "Copacabana",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    numero: "502",
    complemento: "",
    estimated_time: "3-5 dias úteis",
    driver_name: "",
    driver_type: "Terceirizado",
    driver_phone: "",
    transport_obs: "Embalar em cabide — não dobrar",
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
];
