/** Dados contextualizados para o setor Comércio e Varejo (moda/calçados) */

export function isVarejoTheme(theme: unknown): boolean {
  return theme === "varejo";
}

export const VAREJO_PRODUCTS = [
  {
    id: 101,
    sku: "CAM-001",
    name: "Camiseta Oversized Classic",
    stock: 45,
    minimum: 20,
    expiration: "LOTE-2026-A",
    status: "OK" as const,
    price: 89.9,
    description: "Malha premium 100% algodão, corte relaxed fit.",
    image_url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&q=80",
    category: "Moda Masculina",
    is_promo: false,
    barcode: "7891001001001",
    unit_type: "Unidade",
    wholesale_price: 54.9,
  },
  {
    id: 102,
    sku: "TEN-002",
    name: "Tênis Runner Comfort Air",
    stock: 12,
    minimum: 15,
    expiration: "LOTE-2026-B",
    status: "Baixo" as const,
    price: 249.9,
    description: "Amortecimento em gel, cabedal respirável mesh.",
    image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80",
    category: "Calçados",
    is_promo: true,
    promo_price: 199.9,
    barcode: "7892002002002",
    unit_type: "Unidade",
    wholesale_price: 142.0,
  },
  {
    id: 103,
    sku: "CAL-003",
    name: "Calça Cargo Premium",
    stock: 8,
    minimum: 12,
    expiration: "LOTE-2026-C",
    status: "Baixo" as const,
    price: 159.9,
    description: "Algodão com elastano, múltiplos bolsos funcionais.",
    image_url: "https://images.unsplash.com/photo-1473966962644-7e3e24439b0a?w=500&q=80",
    category: "Moda Unissex",
    is_promo: false,
    barcode: "7893003003003",
    unit_type: "Unidade",
    wholesale_price: 98.5,
  },
  {
    id: 104,
    sku: "VES-004",
    name: "Vestido Midi Floral",
    stock: 22,
    minimum: 10,
    expiration: "LOTE-2026-D",
    status: "OK" as const,
    price: 189.9,
    description: "Estampa exclusiva, forro leve, caimento fluido.",
    image_url: "https://images.unsplash.com/photo-1595777457583-95e059a8aead?w=500&q=80",
    category: "Moda Feminina",
    is_promo: false,
    barcode: "7894004004004",
    unit_type: "Unidade",
    wholesale_price: 112.0,
  },
  {
    id: 105,
    sku: "BOL-005",
    name: "Bolsa Tote Couro Sintético",
    stock: 14,
    minimum: 8,
    expiration: "LOTE-2026-E",
    status: "OK" as const,
    price: 129.9,
    description: "Alça reforçada, compartimento interno com zíper.",
    image_url: "https://images.unsplash.com/photo-1584917865442-de89d76a96c8?w=500&q=80",
    category: "Acessórios",
    is_promo: true,
    promo_price: 99.9,
    barcode: "7895005005005",
    unit_type: "Unidade",
    wholesale_price: 72.0,
  },
  {
    id: 106,
    sku: "MOL-006",
    name: "Moletom Classic Canguru",
    stock: 31,
    minimum: 18,
    expiration: "LOTE-2026-F",
    status: "OK" as const,
    price: 119.9,
    description: "Plush interno, capuz com cordão, punho ribana.",
    image_url: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&q=80",
    category: "Moda Unissex",
    is_promo: false,
    barcode: "7896006006006",
    unit_type: "Unidade",
    wholesale_price: 68.0,
  },
];

export function getVarejoDashboard(products = VAREJO_PRODUCTS) {
  const lowStockCount = products.filter((p) => p.stock <= p.minimum).length;
  const nearExpiryCount = products.filter((p) => p.stock <= p.minimum).length;

  return {
    weekly_revenue: 28750,
    weekly_profit: 11240,
    low_stock_count: lowStockCount,
    near_expiry_count: nearExpiryCount,
    revenue_vs_last_week: 14.8,
    profit_vs_last_week: 9.2,
    low_stock_vs_last_week: 3,
    near_expiry_vs_last_week: -1,
    sales_chart: [
      { day: "Seg", revenue: 3200, profit: 1280 },
      { day: "Ter", revenue: 4100, profit: 1650 },
      { day: "Qua", revenue: 3800, profit: 1520 },
      { day: "Qui", revenue: 5200, profit: 2100 },
      { day: "Sex", revenue: 6100, profit: 2480 },
      { day: "Sáb", revenue: 4850, profit: 1940 },
      { day: "Dom", revenue: 1500, profit: 270 },
    ],
    top_sold: [
      { id: 1, name: "Camiseta Oversized Classic", sales: 428 },
      { id: 2, name: "Tênis Runner Comfort Air", sales: 186 },
      { id: 3, name: "Moletom Classic Canguru", sales: 152 },
      { id: 4, name: "Vestido Midi Floral", sales: 94 },
    ],
    inactive_products: [
      { name: "Sandália Flat Verão", days_inactive: 24, stock: 6 },
      { name: "Moletom Classic Canguru", days_inactive: 16, stock: 31 },
      { name: "Calça Cargo Premium", days_inactive: 12, stock: 8 },
    ],
    monthly_totals: {
      gross_revenue: 112400,
      production_costs: 48200,
      invisible_costs: 8900,
      ifood_tax: 0,
      net_profit: 55300,
      margin_ratio: 49.2,
    },
  };
}

export const VAREJO_PROMOTIONS = [
  {
    id: 201,
    title: "Liquidação de Inverno",
    subtitle: "Casacos e moletons — últimas peças da coleção",
    type: "Desconto",
    discount: "-40%",
    recovery: 4200,
    status: "Sucesso",
    active: 1,
  },
  {
    id: 202,
    title: "Leve 3 Camisetas, Pague 2",
    subtitle: "Camiseta Oversized Classic — giro acelerado",
    type: "BOGO",
    discount: "L3P2",
    recovery: 2800,
    status: "Normal",
    active: 0,
  },
  {
    id: 203,
    title: "Combo Tênis + Meia Esportiva",
    subtitle: "Tênis Runner Comfort Air + kit meias",
    type: "Combo",
    discount: "-25%",
    recovery: 1950,
    status: "Aviso",
    active: 0,
  },
];

export const VAREJO_SUPPLIERS = [
  {
    id: 301,
    name: "Têxtil Fios da União",
    contact: "(11) 3344-5566 / vendas@fiosdauniao.com.br",
    category: "Malhas e Tecidos",
    active: 1,
    items: ["Malha PV Premium", "Ribana 1x1", "Moletom Flanelado", "Linha de costura industrial"],
  },
  {
    id: 302,
    name: "Central de Calçados Sul",
    contact: "(51) 99887-1122 / pedidos@calcadossul.com.br",
    category: "Calçados e Solados",
    active: 1,
    items: ["Solado EVA Runner", "Palmilha Comfort Air", "Cadarço elástico", "Caixa display calçado"],
  },
  {
    id: 303,
    name: "Cabides & Tags Embalagens",
    contact: "comercial@cabidestags.com.br",
    category: "Embalagens e PDV",
    active: 1,
    items: ["Cabide acrílico", "Tag RFID", "Sacola kraft branding", "Etiqueta tamanho"],
  },
];

export const VAREJO_ORDERS = [
  {
    id: 401,
    customer_name: "Mariana Souza",
    customer_phone: "(11) 99876-5432",
    type: "Delivery",
    status: "Rota de Envio",
    items: [{ id: 102, name: "Tênis Runner Comfort Air", quantity: 1, price: 249.9 }],
    total_value: 259.9,
    delivery_fee: 10.0,
    cep: "01310-100",
    rua: "Avenida Paulista",
    bairro: "Bela Vista",
    cidade: "São Paulo",
    estado: "SP",
    numero: "1200",
    complemento: "Apto 82",
    estimated_time: "2-3 dias úteis",
    driver_name: "Carlos Costa",
    driver_type: "Terceirizado",
    driver_phone: "(11) 98888-1111",
    transport_obs: "Conferir numeração 38",
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 402,
    customer_name: "Guilherme Santos",
    customer_phone: "(11) 98765-4321",
    type: "Balcão",
    status: "Pronto para Entrega",
    items: [
      { id: 101, name: "Camiseta Oversized Classic", quantity: 2, price: 89.9 },
      { id: 106, name: "Moletom Classic Canguru", quantity: 1, price: 119.9 },
    ],
    total_value: 299.7,
    delivery_fee: 0,
    cep: "",
    rua: "",
    bairro: "",
    cidade: "",
    estado: "",
    numero: "",
    complemento: "",
    estimated_time: "Retirada em loja",
    driver_name: "",
    driver_type: "Próprio",
    driver_phone: "",
    transport_obs: "Separar P e M — provador 2",
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
  {
    id: 403,
    customer_name: "Ana Beatriz Lima",
    customer_phone: "(21) 97777-6666",
    type: "Delivery",
    status: "Em preparo",
    items: [{ id: 104, name: "Vestido Midi Floral", quantity: 1, price: 189.9 }],
    total_value: 199.9,
    delivery_fee: 10.0,
    cep: "22041-080",
    rua: "Rua Barata Ribeiro",
    bairro: "Copacabana",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    numero: "502",
    complemento: "",
    estimated_time: "3-5 dias úteis",
    driver_name: "",
    driver_type: "Terceirizado",
    driver_phone: "",
    transport_obs: "Embalar em cabide — não dobrar",
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
];
